version: 1.0
env:
  variables:
    NODE_ENV: production
    # Any other environment variables you need
  secrets-manager:
    OPENAI_API_KEY: "arn:aws:secretsmanager:region:account-id:secret:your-secret-id" # Load your OpenAI API key from AWS Secrets Manager

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - nvm install 16              # Install Node.js version 16 (as specified in your package.json)
      - npm install                 # Install all the dependencies from package.json
      - npm install -g pm2          # Install PM2 globally to manage the app process

  pre_build:
    commands:
      - echo Pre-building phase...
      - npm run build               # Optional: If your app requires a build step, include it here.

  build:
    commands:
      - echo Starting the Node.js application...
      - pm2 start javarun.js        # Start your Node.js server with PM2

  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - '**/*'  # Include all files from the build output

cache:
  paths:
    - node_modules/**/*
    
